-- Expand the catalog with shade variants and a full beauty aisle.
-- INSERT OR IGNORE so this is safe on top of 0002_seed after a live deploy.
-- Images omit URL query strings so Worker db.exec bootstrap does not treat `?` as binds.

INSERT OR IGNORE INTO products (
  id, name, brand, description, image_url, price, currency, product_url,
  tags, promo_codes, deal_score, availability, restock_estimate, created_at, updated_at
) VALUES
(
  'mac-ruby-woo',
  'Ruby Woo Lipstick',
  'MAC',
  'The iconic blue-red matte lipstick. A true classic red that photographs sharp and lasts through a long night.',
  'https://images.unsplash.com/photo-1522337660859-02fbefca4702',
  23.00, 'USD',
  'https://www.sephora.com/product/mac-ruby-woo',
  '["lipstick","red","makeup","matte","iconic","classic-red"]',
  '[{"code":"RUBY40","label":"40% off matte reds","discountPercent":40}]',
  96, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'mac-russian-red',
  'Russian Red Lipstick',
  'MAC',
  'A deep, slightly orange-red lipstick with a satin finish. The other MAC red people ask for by name.',
  'https://images.unsplash.com/photo-1522337660859-02fbefca4702',
  23.00, 'USD',
  'https://www.sephora.com/product/mac-russian-red',
  '["lipstick","red","makeup","satin","orange-red"]',
  '[{"code":"MACRED25","label":"25% off reds","discountPercent":25}]',
  88, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'mac-chili',
  'Chili Lipstick',
  'MAC',
  'A brick-red lipstick with warm brown undertones. The everyday red that still reads as lipstick, not costume.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  23.00, 'USD',
  'https://www.sephora.com/product/mac-chili',
  '["lipstick","red","makeup","brick","warm","brown-red"]',
  '[{"code":"CHILI18","label":"18% off Chili","discountPercent":18}]',
  82, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'mac-velvet-teddy',
  'Velvet Teddy Lipstick',
  'MAC',
  'A muted brown-nude lipstick. Soft, matte, and the quiet counterpart to MAC reds.',
  'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908',
  23.00, 'USD',
  'https://www.sephora.com/product/mac-velvet-teddy',
  '["lipstick","nude","makeup","matte","brown","beige"]',
  '[{"code":"MAC10","label":"10% off color","discountPercent":10}]',
  74, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'nars-dragon-girl',
  'Dragon Girl Audacious Lipstick',
  'NARS',
  'A vivid true red lipstick with a creamy satin finish. Bold, clean red without going blue or orange.',
  'https://images.unsplash.com/photo-1522337660859-02fbefca4702',
  38.00, 'USD',
  'https://www.sephora.com/product/nars-dragon-girl',
  '["lipstick","red","makeup","satin","true-red","bold"]',
  '[{"code":"NARSRED22","label":"22% off reds","discountPercent":22}]',
  86, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'nars-jungle-red',
  'Jungle Red Audacious Lipstick',
  'NARS',
  'A blue-based crimson red lipstick. Cool, cinematic, and built for a sharp lip line.',
  'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg',
  38.00, 'USD',
  'https://www.sephora.com/product/nars-jungle-red',
  '["lipstick","red","makeup","crimson","blue-red","matte"]',
  '[{"code":"JUNGLE15","label":"15% off","discountPercent":15}]',
  80, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'charlotte-red-carpet',
  'Red Carpet Red Lipstick',
  'Charlotte Tilbury',
  'A glamorous true-red lipstick with a matte-velvet finish. The red-carpet red that still feels modern.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  35.00, 'USD',
  'https://www.sephora.com/product/charlotte-red-carpet',
  '["lipstick","red","makeup","matte","velvet","true-red"]',
  '[{"code":"CTRED20","label":"20% off reds","discountPercent":20}]',
  85, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'fenty-stunna-uncensored',
  'Stunna Lip Paint Uncensored',
  'Fenty Beauty',
  'A longwear liquid red lipstick in shade Uncensored. One coat of precise, punchy red.',
  'https://images.unsplash.com/photo-1522337660859-02fbefca4702',
  26.00, 'USD',
  'https://www.sephora.com/product/fenty-stunna-uncensored',
  '["lipstick","red","makeup","liquid","matte","longwear"]',
  '[{"code":"STUNNA28","label":"28% off Stunna","discountPercent":28}]',
  90, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'dior-rouge-999',
  'Rouge Dior 999',
  'Dior',
  'The house red lipstick. A couture classic-red in a creamy satin that reads luxury from across the room.',
  'https://images.unsplash.com/photo-1522337660859-02fbefca4702',
  50.00, 'USD',
  'https://www.sephora.com/product/dior-rouge-999',
  '["lipstick","red","makeup","satin","luxury","classic-red","iconic"]',
  '[{"code":"DIOR12","label":"12% off color","discountPercent":12}]',
  78, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'ysl-le-rouge',
  'Rouge Pur Couture 01 Le Rouge',
  'Yves Saint Laurent',
  'A golden-case red lipstick in the original Le Rouge. Saturated, fashionable, unapologetic red.',
  'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg',
  48.00, 'USD',
  'https://www.sephora.com/product/ysl-le-rouge',
  '["lipstick","red","makeup","satin","luxury","classic-red"]',
  '[{"code":"YSL15","label":"15% off","discountPercent":15}]',
  79, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'rare-beauty-kind-worthy',
  'Kind Words Matte Lipstick Worthy',
  'Rare Beauty',
  'A soft-matte red lipstick with a comfortable, blurred edge. Everyday red that still searches as lipstick.',
  'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908',
  20.00, 'USD',
  'https://www.sephora.com/product/rare-beauty-kind-worthy',
  '["lipstick","red","makeup","matte","comfortable","blurred"]',
  '[{"code":"KIND20","label":"20% off Kind Words","discountPercent":20}]',
  84, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'maybelline-superstay-pioneer',
  'SuperStay Matte Ink Pioneer',
  'Maybelline',
  'A transfer-proof red liquid lipstick. Drugstore red lipstick that stays put through coffee.',
  'https://images.unsplash.com/photo-1522337660859-02fbefca4702',
  10.00, 'USD',
  'https://www.sephora.com/product/maybelline-superstay-pioneer',
  '["lipstick","red","makeup","matte","liquid","drugstore","longwear"]',
  '[{"code":"PIONEER30","label":"30% off Pioneer","discountPercent":30}]',
  92, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'revlon-fire-ice',
  'Super Lustrous Fire and Ice',
  'Revlon',
  'A coral-red lipstick from the vintage shade vault. Creamy, reflective, old-Hollywood red.',
  'https://images.pexels.com/photos/2113855/pexels-photo-2113855.jpeg',
  9.50, 'USD',
  'https://www.sephora.com/product/revlon-fire-ice',
  '["lipstick","red","makeup","coral","cream","drugstore","vintage"]',
  '[{"code":"REV20","label":"20% off color","discountPercent":20}]',
  83, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'pat-mcgrath-elson',
  'MatteTrance Lipstick Elson',
  'Pat McGrath Labs',
  'A dusty rose-pink lipstick with a luxe velvet matte. Not red — the editorial nude-pink.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  40.00, 'USD',
  'https://www.sephora.com/product/pat-mcgrath-elson',
  '["lipstick","pink","rose","makeup","matte","luxury","nude"]',
  '[{"code":"PMG10","label":"10% off","discountPercent":10}]',
  73, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'pat-mcgrath-elson-red',
  'MatteTrance Lipstick Elson 4',
  'Pat McGrath Labs',
  'A deep ruby-red lipstick with a velvet matte finish. High-pigment red for a couture mouth.',
  'https://images.unsplash.com/photo-1522337660859-02fbefca4702',
  40.00, 'USD',
  'https://www.sephora.com/product/pat-mcgrath-elson-red',
  '["lipstick","red","makeup","matte","ruby","luxury"]',
  '[{"code":"PMGRED18","label":"18% off reds","discountPercent":18}]',
  81, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'clinique-black-honey',
  'Almost Lipstick Black Honey',
  'Clinique',
  'The cult sheer black-cherry lip tint that becomes your lip color. A berry-red stain, not a full lipstick.',
  'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908',
  24.00, 'USD',
  'https://www.sephora.com/product/clinique-black-honey',
  '["lipstick","tint","berry","red","makeup","sheer","cult","cherry"]',
  '[{"code":"HONEY12","label":"12% off","discountPercent":12}]',
  77, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'ilia-balmy-red',
  'Balmy Tint Hydrating Lip Balm Red',
  'Ilia',
  'A clean red lip balm that wears like a tinted lipstick. Hydrating red for no-makeup makeup days.',
  'https://images.pexels.com/photos/2113855/pexels-photo-2113855.jpeg',
  28.00, 'USD',
  'https://www.sephora.com/product/ilia-balmy-red',
  '["lipstick","red","balm","makeup","clean","hydrating","tint"]',
  '[{"code":"ILIA15","label":"15% off","discountPercent":15}]',
  76, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'glossier-ultralip-cachet',
  'Ultralip Cachet',
  'Glossier',
  'A bouncy berry-rose lipstick-balm hybrid. Shine, comfort, and a just-bitten flush.',
  'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908',
  20.00, 'USD',
  'https://www.sephora.com/product/glossier-ultralip-cachet',
  '["lipstick","berry","rose","makeup","balm","shine","pink"]',
  '[{"code":"GLOSS12","label":"12% off","discountPercent":12}]',
  74, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'summer-fridays-cherry',
  'Lip Butter Balm Cherry',
  'Summer Fridays',
  'The buttery balm in a juicy cherry-red tint. Soft color, serious slip.',
  'https://images.pexels.com/photos/2113855/pexels-photo-2113855.jpeg',
  24.00, 'USD',
  'https://www.sephora.com/product/summer-fridays-cherry',
  '["lips","balm","cherry","red","makeup","hydrating","tint"]',
  '[{"code":"SFCHERRY","label":"15% off cherry","discountPercent":15}]',
  80, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'laneige-gummy-bear',
  'Lip Sleeping Mask Gummy Bear',
  'Laneige',
  'Overnight lip mask in the pink gummy-bear scent. Plush, glossy morning lips.',
  'https://images.unsplash.com/photo-1586495777744-4413f21062fa',
  24.00, 'USD',
  'https://www.sephora.com/product/laneige-gummy-bear',
  '["lips","skincare","overnight","k-beauty","pink","mask"]',
  '[{"code":"LANEIGE10","label":"10% off","discountPercent":10}]',
  71, 'in_stock', NULL,
  datetime('now'), datetime('now')
);

INSERT OR IGNORE INTO products (
  id, name, brand, description, image_url, price, currency, product_url,
  tags, promo_codes, deal_score, availability, restock_estimate, created_at, updated_at
) VALUES
(
  'rhode-espresso',
  'Peptide Lip Tint Espresso',
  'Rhode',
  'A deep brown peptide lip tint. Espresso-bar lips with a cushioned, blurred finish.',
  'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908',
  26.00, 'USD',
  'https://www.sephora.com/product/rhode-espresso',
  '["lips","tint","brown","makeup","skincare","cult"]',
  '[]',
  62, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'fenty-gloss-fenty-glow',
  'Gloss Bomb Fenty Glow',
  'Fenty Beauty',
  'A warm nude-pink gloss with gold shimmer. The other universal Gloss Bomb shade.',
  'https://images.pexels.com/photos/2533266/pexels-photo-2533266.jpeg',
  22.00, 'USD',
  'https://www.sephora.com/product/fenty-gloss-fenty-glow',
  '["lips","gloss","makeup","nude","pink","shimmer","inclusive"]',
  '[{"code":"FENTY10","label":"10% off","discountPercent":10}]',
  70, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'rare-beauty-hope',
  'Soft Pinch Liquid Blush Hope',
  'Rare Beauty',
  'A bright coral-pink liquid blush. One dot warms the whole face.',
  'https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg',
  23.00, 'USD',
  'https://www.sephora.com/product/rare-beauty-hope',
  '["blush","makeup","coral","pink","liquid","dewy","vegan"]',
  '[{"code":"HOPE33","label":"33% off Hope","discountPercent":33}]',
  93, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'rare-beauty-encourage',
  'Soft Pinch Liquid Blush Encourage',
  'Rare Beauty',
  'A true red-pink liquid blush. The shade that reads as a pinched flush on deeper skin.',
  'https://images.pexels.com/photos/3373745/pexels-photo-3373745.jpeg',
  23.00, 'USD',
  'https://www.sephora.com/product/rare-beauty-encourage',
  '["blush","makeup","red","pink","liquid","dewy"]',
  '[{"code":"ENCOURAGE18","label":"18% off blush","discountPercent":18}]',
  84, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'rare-beauty-bliss',
  'Soft Pinch Liquid Blush Bliss',
  'Rare Beauty',
  'A soft dusty-rose liquid blush. Quiet, cool, and camera-ready.',
  'https://images.unsplash.com/photo-1610992015732-2449b76344bc',
  23.00, 'USD',
  'https://www.sephora.com/product/rare-beauty-bliss',
  '["blush","makeup","rose","pink","liquid","cool"]',
  '[{"code":"BLISS12","label":"12% off","discountPercent":12}]',
  75, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'glossier-cloud-dusk',
  'Cloud Paint Dusk',
  'Glossier',
  'A gel-cream blush in terracotta-brown. The cool-girl contour-blush hybrid.',
  'https://images.pexels.com/photos/3373745/pexels-photo-3373745.jpeg',
  20.00, 'USD',
  'https://www.sephora.com/product/glossier-cloud-dusk',
  '["blush","makeup","terracotta","brown","dewy","cream"]',
  '[{"code":"DUSK15","label":"15% off","discountPercent":15}]',
  78, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'glossier-cloud-beam',
  'Cloud Paint Beam',
  'Glossier',
  'A sunny peach gel blush. Fresh, sporty color for fair-to-medium skin.',
  'https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg',
  20.00, 'USD',
  'https://www.sephora.com/product/glossier-cloud-beam',
  '["blush","makeup","peach","coral","dewy","cream"]',
  '[{"code":"BEAM10","label":"10% off","discountPercent":10}]',
  72, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'nars-dolce-vita',
  'Dolce Vita Blush',
  'NARS',
  'A muted rose-brown powder blush. The sophisticated sister to Orgasm.',
  'https://images.unsplash.com/photo-1610992015732-2449b76344bc',
  32.00, 'USD',
  'https://www.sephora.com/product/nars-dolce-vita',
  '["blush","makeup","rose","brown","powder","matte","iconic"]',
  '[{"code":"NARS12","label":"12% off color","discountPercent":12}]',
  77, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'nars-exhibit-a',
  'Exhibit A Blush',
  'NARS',
  'A vivid true-red powder blush. High-drama red pigment for cheeks.',
  'https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg',
  32.00, 'USD',
  'https://www.sephora.com/product/nars-exhibit-a',
  '["blush","makeup","red","powder","bold","matte"]',
  '[{"code":"EXHIBIT20","label":"20% off","discountPercent":20}]',
  82, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'saie-dew-blush',
  'Dew Blush',
  'Saie',
  'A clean liquid blush with a wet-skin finish. Buildable color that stays dewy, not sticky.',
  'https://images.pexels.com/photos/3373745/pexels-photo-3373745.jpeg',
  25.00, 'USD',
  'https://www.sephora.com/product/saie-dew-blush',
  '["blush","makeup","clean","dewy","liquid","glow"]',
  '[{"code":"SAIE15","label":"15% off","discountPercent":15}]',
  79, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'milk-cool-cream',
  'Cooling Water Jelly Tint',
  'Milk Makeup',
  'A jelly blush-and-lip stain in a cool berry. Refreshing, sheer, and gym-bag friendly.',
  'https://images.pexels.com/photos/3373736/pexels-photo-3373736.jpeg',
  20.00, 'USD',
  'https://www.sephora.com/product/milk-cool-cream',
  '["blush","makeup","stain","berry","lips","clean","jelly"]',
  '[{"code":"MILK18","label":"18% off","discountPercent":18}]',
  80, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'benefit-dandelion',
  'Dandelion Blush',
  'Benefit',
  'A baby-pink powder blush that brightens tired skin. Soft focus, never stripey.',
  'https://images.unsplash.com/photo-1610992015732-2449b76344bc',
  30.00, 'USD',
  'https://www.sephora.com/product/benefit-dandelion',
  '["blush","makeup","pink","powder","brightening"]',
  '[{"code":"BENE10","label":"10% off","discountPercent":10}]',
  70, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'rms-lip2cheek',
  'Lip2Cheek',
  'RMS Beauty',
  'A cream blush that doubles as a lip color. Clean, creamy, and shade-flexible.',
  'https://images.pexels.com/photos/3373745/pexels-photo-3373745.jpeg',
  36.00, 'USD',
  'https://www.sephora.com/product/rms-lip2cheek',
  '["blush","makeup","cream","lips","clean","multiuse"]',
  '[]',
  64, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'fenty-profiltr-120',
  'Pro Filt''r Soft Matte Foundation 120',
  'Fenty Beauty',
  'A fair, cool foundation shade with a soft-matte, shine-control finish. Inclusive shade 120.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  40.00, 'USD',
  'https://www.sephora.com/product/fenty-profiltr-120',
  '["foundation","makeup","fair","cool","matte","shade-120","inclusive"]',
  '[{"code":"FENTYF15","label":"15% off foundation","discountPercent":15}]',
  76, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'fenty-profiltr-190',
  'Pro Filt''r Soft Matte Foundation 190',
  'Fenty Beauty',
  'A light, warm foundation with yellow undertones. Everyday coverage that does not cake.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  40.00, 'USD',
  'https://www.sephora.com/product/fenty-profiltr-190',
  '["foundation","makeup","light","warm","matte","shade-190","inclusive"]',
  '[{"code":"FENTYF15","label":"15% off foundation","discountPercent":15}]',
  76, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'fenty-profiltr-290',
  'Pro Filt''r Soft Matte Foundation 290',
  'Fenty Beauty',
  'A medium, golden foundation shade. The mid-range match people always need more of.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  40.00, 'USD',
  'https://www.sephora.com/product/fenty-profiltr-290',
  '["foundation","makeup","medium","golden","matte","shade-290","inclusive"]',
  '[{"code":"FENTYF15","label":"15% off foundation","discountPercent":15}]',
  77, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'fenty-profiltr-370',
  'Pro Filt''r Soft Matte Foundation 370',
  'Fenty Beauty',
  'A tan, warm foundation with rich depth. Full coverage that still looks like skin.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  40.00, 'USD',
  'https://www.sephora.com/product/fenty-profiltr-370',
  '["foundation","makeup","tan","warm","matte","shade-370","inclusive"]',
  '[{"code":"FENTYF18","label":"18% off foundation","discountPercent":18}]',
  80, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'fenty-profiltr-445',
  'Pro Filt''r Soft Matte Foundation 445',
  'Fenty Beauty',
  'A deep, neutral foundation shade. High coverage without ashy cast.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  40.00, 'USD',
  'https://www.sephora.com/product/fenty-profiltr-445',
  '["foundation","makeup","deep","neutral","matte","shade-445","inclusive"]',
  '[{"code":"FENTYF18","label":"18% off foundation","discountPercent":18}]',
  80, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'nars-sheer-glow-punjab',
  'Sheer Glow Foundation Punjab',
  'NARS',
  'A light-medium, golden luminous foundation. The glow-skin NARS classic.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  49.00, 'USD',
  'https://www.sephora.com/product/nars-sheer-glow-punjab',
  '["foundation","makeup","light-medium","golden","dewy","luminous"]',
  '[{"code":"NARSF10","label":"10% off","discountPercent":10}]',
  72, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'nars-sheer-glow-syracuse',
  'Sheer Glow Foundation Syracuse',
  'NARS',
  'A medium-deep, warm luminous foundation. Glowy coverage for richer complexions.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  49.00, 'USD',
  'https://www.sephora.com/product/nars-sheer-glow-syracuse',
  '["foundation","makeup","medium-deep","warm","dewy","luminous"]',
  '[{"code":"NARSF10","label":"10% off","discountPercent":10}]',
  72, 'in_stock', NULL,
  datetime('now'), datetime('now')
);

INSERT OR IGNORE INTO products (
  id, name, brand, description, image_url, price, currency, product_url,
  tags, promo_codes, deal_score, availability, restock_estimate, created_at, updated_at
) VALUES
(
  'estee-double-wear-2n1',
  'Double Wear Stay-in-Place 2N1 Desert Beige',
  'Estee Lauder',
  'A transfer-resistant foundation in a best-selling beige. Full coverage that lasts 24 hours.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  48.00, 'USD',
  'https://www.sephora.com/product/estee-double-wear-2n1',
  '["foundation","makeup","beige","matte","longwear","full-coverage"]',
  '[{"code":"DW12","label":"12% off","discountPercent":12}]',
  74, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'estee-double-wear-4w1',
  'Double Wear Stay-in-Place 4W1 Honey Bronze',
  'Estee Lauder',
  'A tan, warm longwear foundation. Honey-bronze depth with serious staying power.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  48.00, 'USD',
  'https://www.sephora.com/product/estee-double-wear-4w1',
  '["foundation","makeup","tan","honey","bronze","matte","longwear"]',
  '[{"code":"DW12","label":"12% off","discountPercent":12}]',
  74, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'ilia-super-serum-st3',
  'Super Serum Skin Tint ST3',
  'Ilia',
  'A clean serum foundation with skincare actives. Sheer-to-medium glow for light skin.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  48.00, 'USD',
  'https://www.sephora.com/product/ilia-super-serum-st3',
  '["foundation","makeup","skincare","tint","clean","light","spf","glow"]',
  '[{"code":"ILIAF15","label":"15% off","discountPercent":15}]',
  78, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'makeup-forever-hd-y225',
  'HD Skin Foundation Y225',
  'Make Up For Ever',
  'A camera-ready foundation in a yellow-light shade. Soft-matte, high definition.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  45.00, 'USD',
  'https://www.sephora.com/product/makeup-forever-hd-y225',
  '["foundation","makeup","light","yellow","matte","pro"]',
  '[]',
  65, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'nars-radiant-custard',
  'Radiant Creamy Concealer Custard',
  'NARS',
  'A light-medium peachy concealer that brightens without creasing. The cult corrector.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  32.00, 'USD',
  'https://www.sephora.com/product/nars-radiant-custard',
  '["concealer","makeup","light-medium","peach","creamy","brightening"]',
  '[{"code":"NARSC12","label":"12% off","discountPercent":12}]',
  73, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'tarte-shape-tape-light',
  'Shape Tape Concealer Light Neutral',
  'Tarte',
  'A full-coverage light concealer. Tape-level coverage for under-eyes and blemishes.',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2',
  32.00, 'USD',
  'https://www.sephora.com/product/tarte-shape-tape-light',
  '["concealer","makeup","light","neutral","full-coverage","matte"]',
  '[{"code":"TAPE15","label":"15% off","discountPercent":15}]',
  75, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'maybelline-sky-high',
  'Lash Sensational Sky High Mascara',
  'Maybelline',
  'A lengthening mascara that fans lashes up and out. Drugstore mascara with prime-time lift.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  12.00, 'USD',
  'https://www.sephora.com/product/maybelline-sky-high',
  '["mascara","makeup","lengthening","drugstore","black","lashes"]',
  '[{"code":"SKY38","label":"38% off Sky High","discountPercent":38}]',
  95, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'too-faced-bts',
  'Better Than Sex Mascara',
  'Too Faced',
  'A volumizing black mascara with a hourglass brush. Dramatic lashes, cult formula.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  29.00, 'USD',
  'https://www.sephora.com/product/too-faced-bts',
  '["mascara","makeup","volumizing","black","lashes","cult"]',
  '[{"code":"BTS20","label":"20% off mascara","discountPercent":20}]',
  85, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'dior-diorshow',
  'Diorshow Mascara',
  'Dior',
  'A couture volumizing mascara. Runway-black lashes with a luxury wand.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  32.00, 'USD',
  'https://www.sephora.com/product/dior-diorshow',
  '["mascara","makeup","volumizing","black","luxury","lashes"]',
  '[{"code":"DIORS12","label":"12% off","discountPercent":12}]',
  74, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'lancome-monsieur-big',
  'Monsieur Big Mascara',
  'Lancome',
  'A big-volume mascara that builds without clumps. Soft black, oversized impact.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  27.00, 'USD',
  'https://www.sephora.com/product/lancome-monsieur-big',
  '["mascara","makeup","volumizing","black","lashes"]',
  '[{"code":"BIG15","label":"15% off","discountPercent":15}]',
  78, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'benefit-theyre-real',
  'They''re Real Magnet Mascara',
  'Benefit',
  'A lifting, separating mascara with a magnetic-feel formula. Long, defined lashes.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  28.00, 'USD',
  'https://www.sephora.com/product/benefit-theyre-real',
  '["mascara","makeup","lengthening","black","lashes"]',
  '[{"code":"REAL10","label":"10% off","discountPercent":10}]',
  71, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'glossier-lash-slick',
  'Lash Slick',
  'Glossier',
  'A thin, natural mascara for your-lashes-but-better. Brown-black, flexible, no crunch.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  18.00, 'USD',
  'https://www.sephora.com/product/glossier-lash-slick',
  '["mascara","makeup","natural","brown-black","lashes","clean"]',
  '[{"code":"SLICK12","label":"12% off","discountPercent":12}]',
  73, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'rare-beauty-perfect-strokes',
  'Perfect Strokes Universal Volumizing Mascara',
  'Rare Beauty',
  'A tubing-adjacent mascara that volumizes without flakes. Inclusive wand for every lash type.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  20.00, 'USD',
  'https://www.sephora.com/product/rare-beauty-perfect-strokes',
  '["mascara","makeup","volumizing","black","inclusive","lashes"]',
  '[{"code":"STROKE15","label":"15% off","discountPercent":15}]',
  77, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'urban-decay-naked3',
  'Naked3 Eyeshadow Palette',
  'Urban Decay',
  'A rose-gold eyeshadow palette. Pink, mauve, and bronze neutrals for everyday lids.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  49.00, 'USD',
  'https://www.sephora.com/product/urban-decay-naked3',
  '["eyeshadow","makeup","palette","rose","gold","pink","neutral"]',
  '[{"code":"NAKED18","label":"18% off palettes","discountPercent":18}]',
  81, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'charlotte-pillow-talk-palette',
  'Pillow Talk Eyeshadow Palette',
  'Charlotte Tilbury',
  'A rosy-nude eyeshadow palette matched to the lipstick. Soft glam, one compact.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  65.00, 'USD',
  'https://www.sephora.com/product/charlotte-pillow-talk-palette',
  '["eyeshadow","makeup","palette","nude","rose","pink","luxury"]',
  '[{"code":"CTP12","label":"12% off","discountPercent":12}]',
  74, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'stila-stay-all-day',
  'Stay All Day Waterproof Liquid Liner',
  'Stila',
  'A precise black liquid eyeliner that does not budge. The wing that survives humidity.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  23.00, 'USD',
  'https://www.sephora.com/product/stila-stay-all-day',
  '["eyeliner","makeup","black","liquid","waterproof","eyes"]',
  '[{"code":"STILA15","label":"15% off","discountPercent":15}]',
  76, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'benefit-gimme-brow',
  'Gimme Brow+ Volumizing Gel',
  'Benefit',
  'A tiny-fiber brow gel that fills sparse arches. Shade 3 is the medium-workhorse.',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348',
  26.00, 'USD',
  'https://www.sephora.com/product/benefit-gimme-brow',
  '["brow","makeup","gel","brown","eyes"]',
  '[{"code":"BROW10","label":"10% off","discountPercent":10}]',
  70, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'ordinary-hyaluronic',
  'Hyaluronic Acid 2% + B5',
  'The Ordinary',
  'A hydrating serum that plumps the look of fine lines. Layer under everything.',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be',
  8.90, 'USD',
  'https://www.sephora.com/product/ordinary-hyaluronic',
  '["skincare","serum","hyaluronic","hydrating","budget","vegan"]',
  '[{"code":"HA35","label":"35% off hyaluronic","discountPercent":35}]',
  94, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'ordinary-retinol',
  'Retinol 0.5% in Squalane',
  'The Ordinary',
  'A beginner-to-mid retinol in a squalane cushion. Night serum for texture and tone.',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be',
  8.00, 'USD',
  'https://www.sephora.com/product/ordinary-retinol',
  '["skincare","serum","retinol","night","budget","anti-aging"]',
  '[{"code":"RET20","label":"20% off retinol","discountPercent":20}]',
  86, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'cerave-hydrating-cleanser',
  'Hydrating Facial Cleanser',
  'CeraVe',
  'A ceramides-and-hyaluronic cleanser that does not strip. Dermatologist staple.',
  'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg',
  16.00, 'USD',
  'https://www.sephora.com/product/cerave-hydrating-cleanser',
  '["skincare","cleanser","ceramides","hydrating","budget","sensitive"]',
  '[{"code":"CERA15","label":"15% off","discountPercent":15}]',
  80, 'in_stock', NULL,
  datetime('now'), datetime('now')
);

INSERT OR IGNORE INTO products (
  id, name, brand, description, image_url, price, currency, product_url,
  tags, promo_codes, deal_score, availability, restock_estimate, created_at, updated_at
) VALUES
(
  'laroche-cicaplast',
  'Cicaplast Baume B5',
  'La Roche-Posay',
  'A repairing balm for compromised, dry, or post-treatment skin. The green-capped savior.',
  'https://images.unsplash.com/photo-1556228720-195a672e8a03',
  16.00, 'USD',
  'https://www.sephora.com/product/laroche-cicaplast',
  '["skincare","balm","repair","sensitive","barrier","soothing"]',
  '[{"code":"CICA18","label":"18% off","discountPercent":18}]',
  83, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'drunk-elephant-c-firma',
  'C-Firma Fresh Day Serum',
  'Drunk Elephant',
  'A 15% vitamin C serum that brightens dull tone. Fresh-mixed potency, citrusy glow.',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be',
  78.00, 'USD',
  'https://www.sephora.com/product/drunk-elephant-c-firma',
  '["skincare","serum","vitamin-c","brightening","antioxidant"]',
  '[{"code":"CFIRMA12","label":"12% off","discountPercent":12}]',
  74, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'sunday-riley-good-genes',
  'Good Genes Lactic Acid Treatment',
  'Sunday Riley',
  'A lactic acid treatment that smooths texture overnight. The cult exfoliating serum.',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be',
  85.00, 'USD',
  'https://www.sephora.com/product/sunday-riley-good-genes',
  '["skincare","serum","exfoliant","lactic","acid","cult","night"]',
  '[{"code":"GENES15","label":"15% off","discountPercent":15}]',
  79, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'inkey-retinol',
  'Retinol Serum',
  'The Inkey List',
  'A gentle, affordable retinol serum. Entry-level night treatment without the drama.',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be',
  12.00, 'USD',
  'https://www.sephora.com/product/inkey-retinol',
  '["skincare","serum","retinol","budget","night","anti-aging"]',
  '[{"code":"INKEY20","label":"20% off","discountPercent":20}]',
  84, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'paulas-choice-bha',
  'Skin Perfecting 2% BHA Liquid Exfoliant',
  'Paula''s Choice',
  'A leave-on salicylic liquid that unclogs pores. The black-bottle BHA everyone recommends.',
  'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg',
  34.00, 'USD',
  'https://www.sephora.com/product/paulas-choice-bha',
  '["skincare","exfoliant","bha","salicylic","pores","toner"]',
  '[{"code":"BHA22","label":"22% off BHA","discountPercent":22}]',
  87, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'supergoop-unseen',
  'Unseen Sunscreen SPF 40',
  'Supergoop',
  'An invisible, primer-like sunscreen. No white cast, makeup-gripping finish.',
  'https://images.unsplash.com/photo-1556228720-195a672e8a03',
  38.00, 'USD',
  'https://www.sephora.com/product/supergoop-unseen',
  '["skincare","sunscreen","spf","primer","makeup"]',
  '[{"code":"SPF15","label":"15% off SPF","discountPercent":15}]',
  81, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'beauty-of-joseon-relief-sun',
  'Relief Sun Rice + Probiotics SPF 50',
  'Beauty of Joseon',
  'A rice-based Korean sunscreen with a dewy, serum-like slip. No cast, daily wear.',
  'https://images.unsplash.com/photo-1556228720-195a672e8a03',
  18.00, 'USD',
  'https://www.sephora.com/product/beauty-of-joseon-relief-sun',
  '["skincare","sunscreen","spf","k-beauty","dewy","rice"]',
  '[{"code":"BOS20","label":"20% off","discountPercent":20}]',
  86, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'glow-recipe-watermelon',
  'Watermelon Glow Niacinamide Dew Drops',
  'Glow Recipe',
  'A glassy highlighting serum with niacinamide. Makeup-artist dew in a pink bottle.',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be',
  35.00, 'USD',
  'https://www.sephora.com/product/glow-recipe-watermelon',
  '["skincare","serum","niacinamide","glow","highlight","dew"]',
  '[{"code":"GLOW18","label":"18% off","discountPercent":18}]',
  82, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'rhode-glazing-milk',
  'Glazing Milk',
  'Rhode',
  'A milky essence that preps skin for glaze. Lightweight hydration with a cult waitlist.',
  'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg',
  29.00, 'USD',
  'https://www.sephora.com/product/rhode-glazing-milk',
  '["skincare","essence","hydrating","milk","cult","glow"]',
  '[]',
  60, 'limited', NULL,
  datetime('now'), datetime('now')
),
(
  'tatcha-rice-wash',
  'The Rice Wash',
  'Tatcha',
  'A creamy Japanese rice cleanser that polishes without tightness. Soft, ceremonial clean.',
  'https://images.unsplash.com/photo-1571781926291-c477ebfd024b',
  36.00, 'USD',
  'https://www.sephora.com/product/tatcha-rice-wash',
  '["skincare","cleanser","rice","luxury","hydrating"]',
  '[{"code":"TATCHA12","label":"12% off","discountPercent":12}]',
  73, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'olehenriksen-banana',
  'Banana Bright+ Vitamin C Serum',
  'Ole Henriksen',
  'A banana-yellow vitamin C serum that brightens dark circles and tone. Citrus-cream scent.',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be',
  48.00, 'USD',
  'https://www.sephora.com/product/olehenriksen-banana',
  '["skincare","serum","vitamin-c","brightening","eyes"]',
  '[{"code":"BANANA15","label":"15% off","discountPercent":15}]',
  77, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'summer-fridays-cloud-dew',
  'Cloud Dew Gel Cream',
  'Summer Fridays',
  'A water-gel moisturizer that cools and plumps. Dewy, non-greasy, clean-feeling.',
  'https://images.unsplash.com/photo-1556228720-195a672e8a03',
  38.00, 'USD',
  'https://www.sephora.com/product/summer-fridays-cloud-dew',
  '["skincare","moisturizer","gel","hydrating","dewy","clean"]',
  '[{"code":"CLOUD12","label":"12% off","discountPercent":12}]',
  74, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'laneige-cream-skin',
  'Cream Skin Toner & Moisturizer',
  'Laneige',
  'A milky toner-moisturizer hybrid. K-beauty hydration that layers under makeup.',
  'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg',
  34.00, 'USD',
  'https://www.sephora.com/product/laneige-cream-skin',
  '["skincare","toner","moisturizer","k-beauty","hydrating","milk"]',
  '[{"code":"CREAMSKIN","label":"15% off","discountPercent":15}]',
  78, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'glossier-you',
  'Glossier You Eau de Parfum',
  'Glossier',
  'A skin-musk fragrance with pink pepper and iris. Your-skin-but-warmer.',
  'https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg',
  68.00, 'USD',
  'https://www.sephora.com/product/glossier-you',
  '["fragrance","musk","iris","skin","cult"]',
  '[{"code":"YOU15","label":"15% off","discountPercent":15}]',
  80, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'replica-fireplace',
  'Replica By the Fireplace',
  'Maison Margiela',
  'A smoky vanilla chestnut fragrance. Cashmere-sweater warmth in a replica bottle.',
  'https://images.unsplash.com/photo-1617897903246-719242758050',
  144.00, 'USD',
  'https://www.sephora.com/product/replica-fireplace',
  '["fragrance","vanilla","smoke","woody","cozy","unisex"]',
  '[{"code":"REPLICA12","label":"12% off","discountPercent":12}]',
  74, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'replica-lazy-sunday',
  'Replica Lazy Sunday Morning',
  'Maison Margiela',
  'A clean musk-and-floral fragrance. Fresh sheets, pear, and quiet luxury.',
  'https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg',
  144.00, 'USD',
  'https://www.sephora.com/product/replica-lazy-sunday',
  '["fragrance","musk","floral","clean","fresh","unisex"]',
  '[{"code":"REPLICA12","label":"12% off","discountPercent":12}]',
  73, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'le-labo-santal-33',
  'Santal 33',
  'Le Labo',
  'The cult sandalwood fragrance. Leather, cedar, and that instantly recognizable trail.',
  'https://images.pexels.com/photos/1377034/pexels-photo-1377034.jpeg',
  215.00, 'USD',
  'https://www.sephora.com/product/le-labo-santal-33',
  '["fragrance","sandalwood","woody","cult","unisex","luxury"]',
  '[{"code":"SANTAL8","label":"8% off","discountPercent":8}]',
  68, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'jo-malone-peony',
  'Peony & Blush Suede Cologne',
  'Jo Malone',
  'A juicy peony fragrance with suede softness. Floral, pretty, gift-boxed.',
  'https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg',
  160.00, 'USD',
  'https://www.sephora.com/product/jo-malone-peony',
  '["fragrance","floral","peony","blush","luxury"]',
  '[{"code":"JM10","label":"10% off","discountPercent":10}]',
  70, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'ysl-libre',
  'Libre Eau de Parfum',
  'Yves Saint Laurent',
  'A lavender-orange-blossom fragrance with a modern musk. Bold, golden, daytime-to-dinner.',
  'https://images.unsplash.com/photo-1617897903246-719242758050',
  148.00, 'USD',
  'https://www.sephora.com/product/ysl-libre',
  '["fragrance","floral","lavender","luxury","womens"]',
  '[{"code":"LIBRE12","label":"12% off","discountPercent":12}]',
  74, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'chanel-coco-mademoiselle',
  'Coco Mademoiselle Eau de Parfum',
  'Chanel',
  'A sparkling orange-patchouli classic. The Chanel that reads as confident, not powdery.',
  'https://images.unsplash.com/photo-1617897903246-719242758050',
  148.00, 'USD',
  'https://www.sephora.com/product/chanel-coco-mademoiselle',
  '["fragrance","citrus","patchouli","luxury","iconic"]',
  '[]',
  58, 'in_stock', NULL,
  datetime('now'), datetime('now')
);

INSERT OR IGNORE INTO products (
  id, name, brand, description, image_url, price, currency, product_url,
  tags, promo_codes, deal_score, availability, restock_estimate, created_at, updated_at
) VALUES
(
  'miss-dior',
  'Miss Dior Eau de Parfum',
  'Dior',
  'A rosy, musky Miss Dior. Fresh-cut flowers with a couture bow.',
  'https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg',
  142.00, 'USD',
  'https://www.sephora.com/product/miss-dior',
  '["fragrance","rose","floral","luxury","womens"]',
  '[{"code":"MISSD10","label":"10% off","discountPercent":10}]',
  69, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'kayali-vanilla-28',
  'Vanilla | 28',
  'Kayali',
  'A gourmand vanilla fragrance with brown sugar and musk. Sweet, layered, late-night.',
  'https://images.unsplash.com/photo-1617897903246-719242758050',
  88.00, 'USD',
  'https://www.sephora.com/product/kayali-vanilla-28',
  '["fragrance","vanilla","gourmand","sweet","musk"]',
  '[{"code":"VANILLA20","label":"20% off vanilla","discountPercent":20}]',
  85, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'phlur-missing-person',
  'Missing Person',
  'Phlur',
  'A skin-scent fragrance that smells like a worn T-shirt. Soft musk, clean, intimate.',
  'https://images.pexels.com/photos/965989/pexels-photo-965989.jpeg',
  99.00, 'USD',
  'https://www.sephora.com/product/phlur-missing-person',
  '["fragrance","musk","skin","clean","cult"]',
  '[{"code":"PHLUR15","label":"15% off","discountPercent":15}]',
  78, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'olaplex-no3',
  'No.3 Hair Perfector',
  'Olaplex',
  'A bond-building hair treatment. The at-home step that makes color and heat less tragic.',
  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
  30.00, 'USD',
  'https://www.sephora.com/product/olaplex-no3',
  '["hair","treatment","bonds","repair","cult"]',
  '[{"code":"OLAP15","label":"15% off","discountPercent":15}]',
  80, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'olaplex-no7',
  'No.7 Bonding Oil',
  'Olaplex',
  'A weightless bonding hair oil for shine and heat protection. Glass-hair finish.',
  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
  30.00, 'USD',
  'https://www.sephora.com/product/olaplex-no7',
  '["hair","oil","shine","heat","repair"]',
  '[{"code":"OLAP15","label":"15% off","discountPercent":15}]',
  79, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'ouai-leave-in',
  'Leave In Conditioner',
  'Ouai',
  'A detangling leave-in mist with a signature scent. Fine-hair friendly slip.',
  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
  28.00, 'USD',
  'https://www.sephora.com/product/ouai-leave-in',
  '["hair","leave-in","conditioner","detangle","mist"]',
  '[{"code":"OUAI12","label":"12% off","discountPercent":12}]',
  73, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'living-proof-dry',
  'Perfect Hair Day Dry Shampoo',
  'Living Proof',
  'A residue-minimal dry shampoo that actually cleans. Day-two hair, day-one energy.',
  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
  29.00, 'USD',
  'https://www.sephora.com/product/living-proof-dry',
  '["hair","dry-shampoo","volume","refresh"]',
  '[{"code":"LIVING18","label":"18% off","discountPercent":18}]',
  81, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'colorwow-dream-coat',
  'Dream Coat Supernatural Spray',
  'Color Wow',
  'An anti-humidity hair spray that seals the cuticle. Frizz-glass for humid weeks.',
  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
  28.00, 'USD',
  'https://www.sephora.com/product/colorwow-dream-coat',
  '["hair","spray","anti-frizz","humidity","shine","cult"]',
  '[{"code":"DREAM20","label":"20% off Dream Coat","discountPercent":20}]',
  86, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'amika-soulfood',
  'Soulfood Nourishing Mask',
  'Amika',
  'A rich hair mask with sea buckthorn. Weekly moisture for dry, colored ends.',
  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
  32.00, 'USD',
  'https://www.sephora.com/product/amika-soulfood',
  '["hair","mask","treatment","hydrating","repair"]',
  '[{"code":"AMIKA15","label":"15% off","discountPercent":15}]',
  77, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'pattern-leave-in',
  'Leave-In Conditioner',
  'Pattern',
  'A curl-defining leave-in for coils and curls. Slip, moisture, and no crunch.',
  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
  25.00, 'USD',
  'https://www.sephora.com/product/pattern-leave-in',
  '["hair","leave-in","curls","coils","hydrating","textured"]',
  '[{"code":"PATTERN15","label":"15% off","discountPercent":15}]',
  78, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'kerastase-elixir',
  'Elixir Ultime Hair Oil',
  'Kerastase',
  'A luxury shine oil for polished ends. Formal-event hair in a gold bottle.',
  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
  50.00, 'USD',
  'https://www.sephora.com/product/kerastase-elixir',
  '["hair","oil","shine","luxury","frizz"]',
  '[{"code":"KERA10","label":"10% off","discountPercent":10}]',
  70, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'essie-ballet-slippers',
  'Ballet Slippers Nail Polish',
  'Essie',
  'The barely-there pink nail polish. Manicure classic for every skin tone.',
  'https://images.unsplash.com/photo-1604654894610-df63bc536371',
  10.00, 'USD',
  'https://www.sephora.com/product/essie-ballet-slippers',
  '["nails","polish","pink","nude","manicure","sheer"]',
  '[{"code":"ESSIE12","label":"12% off","discountPercent":12}]',
  72, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'essie-wicked',
  'Wicked Nail Polish',
  'Essie',
  'A deep blood-red nail polish. The red manicure that matches a red lipstick.',
  'https://images.unsplash.com/photo-1604654894610-df63bc536371',
  10.00, 'USD',
  'https://www.sephora.com/product/essie-wicked',
  '["nails","polish","red","manicure","classic-red","cream"]',
  '[{"code":"WICKED36","label":"36% off Wicked","discountPercent":36}]',
  94, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'opi-big-apple-red',
  'Big Apple Red Nail Lacquer',
  'OPI',
  'A true red nail lacquer. The New York red that sits next to a red lipstick in the bag.',
  'https://images.unsplash.com/photo-1604654894610-df63bc536371',
  12.00, 'USD',
  'https://www.sephora.com/product/opi-big-apple-red',
  '["nails","polish","red","manicure","classic-red"]',
  '[{"code":"OPI20","label":"20% off reds","discountPercent":20}]',
  84, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'olivejune-poppy',
  'Poppy Nail Polish',
  'Olive & June',
  'A clean coral-red nail polish with a wide brush. At-home salon red.',
  'https://images.unsplash.com/photo-1604654894610-df63bc536371',
  9.00, 'USD',
  'https://www.sephora.com/product/olivejune-poppy',
  '["nails","polish","coral","red","manicure","clean"]',
  '[{"code":"OJ15","label":"15% off","discountPercent":15}]',
  76, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'nails-inc-kale',
  'NailKale Superfood Base Coat',
  'Nails Inc',
  'A kale-infused base coat that strengthens peeling nails. The green-bottle prep step.',
  'https://images.unsplash.com/photo-1604654894610-df63bc536371',
  15.00, 'USD',
  'https://www.sephora.com/product/nails-inc-kale',
  '["nails","base-coat","care","strengthening","treatment"]',
  '[{"code":"KALE10","label":"10% off","discountPercent":10}]',
  68, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'the-gelbottle-builder',
  'The GelBottle Builder Gel',
  'The GelBottle',
  'A builder gel for structured manicures. Salon overlay in a bottle.',
  'https://images.unsplash.com/photo-1604654894610-df63bc536371',
  22.00, 'USD',
  'https://www.sephora.com/product/the-gelbottle-builder',
  '["nails","gel","builder","manicure","salon"]',
  '[]',
  55, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'beautyblender-original',
  'Original Beautyblender',
  'Beautyblender',
  'The pink makeup sponge that bounce-blends foundation. Wet, bounce, blend.',
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e',
  20.00, 'USD',
  'https://www.sephora.com/product/beautyblender-original',
  '["tools","sponge","makeup","blender","foundation"]',
  '[{"code":"BB20","label":"20% off sponge","discountPercent":20}]',
  83, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'real-techniques-sponge',
  'Miracle Complexion Sponge',
  'Real Techniques',
  'A budget makeup sponge with a pointed tip for under-eyes. Drugstore blender that works.',
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e',
  7.00, 'USD',
  'https://www.sephora.com/product/real-techniques-sponge',
  '["tools","sponge","makeup","blender","drugstore","foundation"]',
  '[{"code":"RT25","label":"25% off tools","discountPercent":25}]',
  88, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'morphe-face-brush-set',
  'Face Brush Set',
  'Morphe',
  'A face brush set for powder, blush, and contour. Soft synthetics, gold ferrules.',
  'https://images.unsplash.com/photo-1512496015851-a90fb52d41c1',
  28.00, 'USD',
  'https://www.sephora.com/product/morphe-face-brush-set',
  '["tools","brushes","makeup","blush","powder","set"]',
  '[{"code":"MORPHE18","label":"18% off brushes","discountPercent":18}]',
  80, 'in_stock', NULL,
  datetime('now'), datetime('now')
);

INSERT OR IGNORE INTO products (
  id, name, brand, description, image_url, price, currency, product_url,
  tags, promo_codes, deal_score, availability, restock_estimate, created_at, updated_at
) VALUES
(
  'shu-eyelash-curler',
  'Eyelash Curler',
  'Shu Uemura',
  'The makeup-artist eyelash curler. A wide clamp that does not pinch.',
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e',
  22.00, 'USD',
  'https://www.sephora.com/product/shu-eyelash-curler',
  '["tools","curler","lashes","makeup","eyes"]',
  '[{"code":"SHU12","label":"12% off","discountPercent":12}]',
  72, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'tweezerman-slant',
  'Slant Tweezer',
  'Tweezerman',
  'A precision slant tweezer for brows. The gold standard of the makeup bag.',
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e',
  25.00, 'USD',
  'https://www.sephora.com/product/tweezerman-slant',
  '["tools","tweezers","brows","makeup"]',
  '[{"code":"TWEEZ10","label":"10% off","discountPercent":10}]',
  69, 'in_stock', NULL,
  datetime('now'), datetime('now')
),
(
  'ghd-glide',
  'Glide Hot Brush',
  'ghd',
  'A heated smoothing brush for blowout shine. Hotel-bathroom polish at home.',
  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9',
  169.00, 'USD',
  'https://www.sephora.com/product/ghd-glide',
  '["tools","hair","hot-brush","smoothing","heat","luxury"]',
  '[{"code":"GHD8","label":"8% off","discountPercent":8}]',
  64, 'in_stock', NULL,
  datetime('now'), datetime('now')
);

INSERT OR IGNORE INTO price_history (product_id, price, recorded_at) VALUES
  ('mac-ruby-woo', 25.76, datetime('now', '-14 days')),
  ('mac-ruby-woo', 23.00, datetime('now')),
  ('mac-russian-red', 23.92, datetime('now', '-14 days')),
  ('mac-russian-red', 23.00, datetime('now')),
  ('mac-chili', 23.92, datetime('now', '-14 days')),
  ('mac-chili', 23.00, datetime('now')),
  ('mac-velvet-teddy', 23.92, datetime('now', '-14 days')),
  ('mac-velvet-teddy', 23.00, datetime('now')),
  ('nars-dragon-girl', 39.52, datetime('now', '-14 days')),
  ('nars-dragon-girl', 38.00, datetime('now')),
  ('nars-jungle-red', 39.52, datetime('now', '-14 days')),
  ('nars-jungle-red', 38.00, datetime('now')),
  ('charlotte-red-carpet', 36.40, datetime('now', '-14 days')),
  ('charlotte-red-carpet', 35.00, datetime('now')),
  ('fenty-stunna-uncensored', 27.04, datetime('now', '-14 days')),
  ('fenty-stunna-uncensored', 26.00, datetime('now')),
  ('dior-rouge-999', 52.00, datetime('now', '-14 days')),
  ('dior-rouge-999', 50.00, datetime('now')),
  ('ysl-le-rouge', 49.92, datetime('now', '-14 days')),
  ('ysl-le-rouge', 48.00, datetime('now')),
  ('rare-beauty-kind-worthy', 20.80, datetime('now', '-14 days')),
  ('rare-beauty-kind-worthy', 20.00, datetime('now')),
  ('maybelline-superstay-pioneer', 11.20, datetime('now', '-14 days')),
  ('maybelline-superstay-pioneer', 10.00, datetime('now')),
  ('revlon-fire-ice', 9.88, datetime('now', '-14 days')),
  ('revlon-fire-ice', 9.50, datetime('now')),
  ('pat-mcgrath-elson', 41.60, datetime('now', '-14 days')),
  ('pat-mcgrath-elson', 40.00, datetime('now')),
  ('pat-mcgrath-elson-red', 41.60, datetime('now', '-14 days')),
  ('pat-mcgrath-elson-red', 40.00, datetime('now')),
  ('clinique-black-honey', 24.96, datetime('now', '-14 days')),
  ('clinique-black-honey', 24.00, datetime('now')),
  ('ilia-balmy-red', 29.12, datetime('now', '-14 days')),
  ('ilia-balmy-red', 28.00, datetime('now')),
  ('glossier-ultralip-cachet', 20.80, datetime('now', '-14 days')),
  ('glossier-ultralip-cachet', 20.00, datetime('now')),
  ('summer-fridays-cherry', 24.96, datetime('now', '-14 days')),
  ('summer-fridays-cherry', 24.00, datetime('now')),
  ('laneige-gummy-bear', 24.96, datetime('now', '-14 days')),
  ('laneige-gummy-bear', 24.00, datetime('now')),
  ('rhode-espresso', 27.04, datetime('now', '-14 days')),
  ('rhode-espresso', 26.00, datetime('now')),
  ('fenty-gloss-fenty-glow', 22.88, datetime('now', '-14 days')),
  ('fenty-gloss-fenty-glow', 22.00, datetime('now')),
  ('rare-beauty-hope', 25.76, datetime('now', '-14 days')),
  ('rare-beauty-hope', 23.00, datetime('now')),
  ('rare-beauty-encourage', 23.92, datetime('now', '-14 days')),
  ('rare-beauty-encourage', 23.00, datetime('now')),
  ('rare-beauty-bliss', 23.92, datetime('now', '-14 days')),
  ('rare-beauty-bliss', 23.00, datetime('now')),
  ('glossier-cloud-dusk', 20.80, datetime('now', '-14 days')),
  ('glossier-cloud-dusk', 20.00, datetime('now')),
  ('glossier-cloud-beam', 20.80, datetime('now', '-14 days')),
  ('glossier-cloud-beam', 20.00, datetime('now')),
  ('nars-dolce-vita', 33.28, datetime('now', '-14 days')),
  ('nars-dolce-vita', 32.00, datetime('now')),
  ('nars-exhibit-a', 33.28, datetime('now', '-14 days')),
  ('nars-exhibit-a', 32.00, datetime('now')),
  ('saie-dew-blush', 26.00, datetime('now', '-14 days')),
  ('saie-dew-blush', 25.00, datetime('now')),
  ('milk-cool-cream', 20.80, datetime('now', '-14 days')),
  ('milk-cool-cream', 20.00, datetime('now')),
  ('benefit-dandelion', 31.20, datetime('now', '-14 days')),
  ('benefit-dandelion', 30.00, datetime('now')),
  ('rms-lip2cheek', 37.44, datetime('now', '-14 days')),
  ('rms-lip2cheek', 36.00, datetime('now')),
  ('fenty-profiltr-120', 41.60, datetime('now', '-14 days')),
  ('fenty-profiltr-120', 40.00, datetime('now')),
  ('fenty-profiltr-190', 41.60, datetime('now', '-14 days')),
  ('fenty-profiltr-190', 40.00, datetime('now')),
  ('fenty-profiltr-290', 41.60, datetime('now', '-14 days')),
  ('fenty-profiltr-290', 40.00, datetime('now')),
  ('fenty-profiltr-370', 41.60, datetime('now', '-14 days')),
  ('fenty-profiltr-370', 40.00, datetime('now')),
  ('fenty-profiltr-445', 41.60, datetime('now', '-14 days')),
  ('fenty-profiltr-445', 40.00, datetime('now')),
  ('nars-sheer-glow-punjab', 50.96, datetime('now', '-14 days')),
  ('nars-sheer-glow-punjab', 49.00, datetime('now')),
  ('nars-sheer-glow-syracuse', 50.96, datetime('now', '-14 days')),
  ('nars-sheer-glow-syracuse', 49.00, datetime('now')),
  ('estee-double-wear-2n1', 49.92, datetime('now', '-14 days')),
  ('estee-double-wear-2n1', 48.00, datetime('now')),
  ('estee-double-wear-4w1', 49.92, datetime('now', '-14 days')),
  ('estee-double-wear-4w1', 48.00, datetime('now')),
  ('ilia-super-serum-st3', 49.92, datetime('now', '-14 days')),
  ('ilia-super-serum-st3', 48.00, datetime('now')),
  ('makeup-forever-hd-y225', 46.80, datetime('now', '-14 days')),
  ('makeup-forever-hd-y225', 45.00, datetime('now')),
  ('nars-radiant-custard', 33.28, datetime('now', '-14 days')),
  ('nars-radiant-custard', 32.00, datetime('now')),
  ('tarte-shape-tape-light', 33.28, datetime('now', '-14 days')),
  ('tarte-shape-tape-light', 32.00, datetime('now')),
  ('maybelline-sky-high', 13.44, datetime('now', '-14 days')),
  ('maybelline-sky-high', 12.00, datetime('now')),
  ('too-faced-bts', 30.16, datetime('now', '-14 days')),
  ('too-faced-bts', 29.00, datetime('now')),
  ('dior-diorshow', 33.28, datetime('now', '-14 days')),
  ('dior-diorshow', 32.00, datetime('now')),
  ('lancome-monsieur-big', 28.08, datetime('now', '-14 days')),
  ('lancome-monsieur-big', 27.00, datetime('now')),
  ('benefit-theyre-real', 29.12, datetime('now', '-14 days')),
  ('benefit-theyre-real', 28.00, datetime('now')),
  ('glossier-lash-slick', 18.72, datetime('now', '-14 days')),
  ('glossier-lash-slick', 18.00, datetime('now')),
  ('rare-beauty-perfect-strokes', 20.80, datetime('now', '-14 days')),
  ('rare-beauty-perfect-strokes', 20.00, datetime('now')),
  ('urban-decay-naked3', 50.96, datetime('now', '-14 days')),
  ('urban-decay-naked3', 49.00, datetime('now')),
  ('charlotte-pillow-talk-palette', 67.60, datetime('now', '-14 days')),
  ('charlotte-pillow-talk-palette', 65.00, datetime('now')),
  ('stila-stay-all-day', 23.92, datetime('now', '-14 days')),
  ('stila-stay-all-day', 23.00, datetime('now')),
  ('benefit-gimme-brow', 27.04, datetime('now', '-14 days')),
  ('benefit-gimme-brow', 26.00, datetime('now')),
  ('ordinary-hyaluronic', 9.97, datetime('now', '-14 days')),
  ('ordinary-hyaluronic', 8.90, datetime('now')),
  ('ordinary-retinol', 8.32, datetime('now', '-14 days')),
  ('ordinary-retinol', 8.00, datetime('now')),
  ('cerave-hydrating-cleanser', 16.64, datetime('now', '-14 days')),
  ('cerave-hydrating-cleanser', 16.00, datetime('now')),
  ('laroche-cicaplast', 16.64, datetime('now', '-14 days')),
  ('laroche-cicaplast', 16.00, datetime('now')),
  ('drunk-elephant-c-firma', 81.12, datetime('now', '-14 days')),
  ('drunk-elephant-c-firma', 78.00, datetime('now')),
  ('sunday-riley-good-genes', 88.40, datetime('now', '-14 days')),
  ('sunday-riley-good-genes', 85.00, datetime('now')),
  ('inkey-retinol', 12.48, datetime('now', '-14 days')),
  ('inkey-retinol', 12.00, datetime('now')),
  ('paulas-choice-bha', 35.36, datetime('now', '-14 days')),
  ('paulas-choice-bha', 34.00, datetime('now')),
  ('supergoop-unseen', 39.52, datetime('now', '-14 days')),
  ('supergoop-unseen', 38.00, datetime('now')),
  ('beauty-of-joseon-relief-sun', 18.72, datetime('now', '-14 days')),
  ('beauty-of-joseon-relief-sun', 18.00, datetime('now')),
  ('glow-recipe-watermelon', 36.40, datetime('now', '-14 days')),
  ('glow-recipe-watermelon', 35.00, datetime('now')),
  ('rhode-glazing-milk', 30.16, datetime('now', '-14 days')),
  ('rhode-glazing-milk', 29.00, datetime('now')),
  ('tatcha-rice-wash', 37.44, datetime('now', '-14 days')),
  ('tatcha-rice-wash', 36.00, datetime('now')),
  ('olehenriksen-banana', 49.92, datetime('now', '-14 days')),
  ('olehenriksen-banana', 48.00, datetime('now')),
  ('summer-fridays-cloud-dew', 39.52, datetime('now', '-14 days')),
  ('summer-fridays-cloud-dew', 38.00, datetime('now')),
  ('laneige-cream-skin', 35.36, datetime('now', '-14 days')),
  ('laneige-cream-skin', 34.00, datetime('now')),
  ('glossier-you', 70.72, datetime('now', '-14 days')),
  ('glossier-you', 68.00, datetime('now')),
  ('replica-fireplace', 149.76, datetime('now', '-14 days')),
  ('replica-fireplace', 144.00, datetime('now')),
  ('replica-lazy-sunday', 149.76, datetime('now', '-14 days')),
  ('replica-lazy-sunday', 144.00, datetime('now')),
  ('le-labo-santal-33', 223.60, datetime('now', '-14 days')),
  ('le-labo-santal-33', 215.00, datetime('now')),
  ('jo-malone-peony', 166.40, datetime('now', '-14 days')),
  ('jo-malone-peony', 160.00, datetime('now')),
  ('ysl-libre', 153.92, datetime('now', '-14 days')),
  ('ysl-libre', 148.00, datetime('now')),
  ('chanel-coco-mademoiselle', 153.92, datetime('now', '-14 days')),
  ('chanel-coco-mademoiselle', 148.00, datetime('now')),
  ('miss-dior', 147.68, datetime('now', '-14 days')),
  ('miss-dior', 142.00, datetime('now')),
  ('kayali-vanilla-28', 91.52, datetime('now', '-14 days')),
  ('kayali-vanilla-28', 88.00, datetime('now')),
  ('phlur-missing-person', 102.96, datetime('now', '-14 days')),
  ('phlur-missing-person', 99.00, datetime('now')),
  ('olaplex-no3', 31.20, datetime('now', '-14 days')),
  ('olaplex-no3', 30.00, datetime('now')),
  ('olaplex-no7', 31.20, datetime('now', '-14 days')),
  ('olaplex-no7', 30.00, datetime('now')),
  ('ouai-leave-in', 29.12, datetime('now', '-14 days')),
  ('ouai-leave-in', 28.00, datetime('now')),
  ('living-proof-dry', 30.16, datetime('now', '-14 days')),
  ('living-proof-dry', 29.00, datetime('now')),
  ('colorwow-dream-coat', 29.12, datetime('now', '-14 days')),
  ('colorwow-dream-coat', 28.00, datetime('now')),
  ('amika-soulfood', 33.28, datetime('now', '-14 days')),
  ('amika-soulfood', 32.00, datetime('now')),
  ('pattern-leave-in', 26.00, datetime('now', '-14 days')),
  ('pattern-leave-in', 25.00, datetime('now')),
  ('kerastase-elixir', 52.00, datetime('now', '-14 days')),
  ('kerastase-elixir', 50.00, datetime('now')),
  ('essie-ballet-slippers', 10.40, datetime('now', '-14 days')),
  ('essie-ballet-slippers', 10.00, datetime('now')),
  ('essie-wicked', 11.20, datetime('now', '-14 days')),
  ('essie-wicked', 10.00, datetime('now')),
  ('opi-big-apple-red', 12.48, datetime('now', '-14 days')),
  ('opi-big-apple-red', 12.00, datetime('now')),
  ('olivejune-poppy', 9.36, datetime('now', '-14 days')),
  ('olivejune-poppy', 9.00, datetime('now')),
  ('nails-inc-kale', 15.60, datetime('now', '-14 days')),
  ('nails-inc-kale', 15.00, datetime('now')),
  ('the-gelbottle-builder', 22.88, datetime('now', '-14 days')),
  ('the-gelbottle-builder', 22.00, datetime('now')),
  ('beautyblender-original', 20.80, datetime('now', '-14 days')),
  ('beautyblender-original', 20.00, datetime('now')),
  ('real-techniques-sponge', 7.28, datetime('now', '-14 days')),
  ('real-techniques-sponge', 7.00, datetime('now')),
  ('morphe-face-brush-set', 29.12, datetime('now', '-14 days')),
  ('morphe-face-brush-set', 28.00, datetime('now')),
  ('shu-eyelash-curler', 22.88, datetime('now', '-14 days')),
  ('shu-eyelash-curler', 22.00, datetime('now')),
  ('tweezerman-slant', 26.00, datetime('now', '-14 days')),
  ('tweezerman-slant', 25.00, datetime('now')),
  ('ghd-glide', 175.76, datetime('now', '-14 days')),
  ('ghd-glide', 169.00, datetime('now'));
